server:
  log_level: info

# prometheus:
#   wal_directory: /tmp/wal
#   global:
#     scrape_interval: 5s
#   configs:
#     - name: app-metrics
#       scrape_configs:
#         - job_name: 'python-app'
#           static_configs:
#             - targets: ['localhost:8000']  # Scrape your uvicorn /metrics

loki:
  configs:
    - name: default
      clients:
        - url: "http://host.docker.internal:3100/loki/api/v1/push"
      positions:
        filename: /tmp/positions.yaml
      scrape_configs:
        - job_name: python-logs
          static_configs:
            - targets: ['localhost']
              labels:
                job: python-app
                __path__: /tmp/app.log  # Or any log file your app writes
